# Controllers Package (Primary Adapters)
# Can depend on application layer and HTTP delivery adapters (serializers)
# Controllers CANNOT import from domain/ (aggregates, entities, ports)
# Controllers CANNOT import from infrastructure/persistence/ (repositories)
enforce_dependencies: true
dependencies:
  - "../../engines/cat_content/app/application/cat_content"
  - "../../engines/cat_content/app/infrastructure/cat_content/http"
