# Bounded Context boundary - isolates this engine from others
enforce_dependencies: true
enforce_privacy: true

# Add dependencies to other engines as needed:
# dependencies:
#   - "../../engines/orders"      # Only sees orders/app/public/*
